baseURL = 'https://hsandid.github.io/notes'
languageCode = 'en-us'
title = 'Notes'
# This defines how dates are formatted
defaultContentLanguage = "en-gb"

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] # ignore error of loading additional scripts.

[module]
  [[module.imports]]
    path = "github.com/vaga/hugo-theme-m10c"
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 4 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

[[params.socialIcons]]
name = "github"
url = "https://github.com/hsandid"

[Languages.en-gb]
  languageName = "English"
  languageCode = "en-gb"
  contentDir = "content"
  weight = 1

# Green theme
[params.style]
  darkestColor = "#315659"
  darkColor = "#253031"
  lightColor = "#96a879"
  lightestColor = "#fff"
  primaryColor = "#dad865"
